version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://survey_user:survey_user@db:5432/surveydb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_user
      POSTGRES_DB: surveydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
